"""Inject original assets into AI articles so they're non-derivative.

For each post, generate ONE of:
  * a comparison table
  * a "TL;DR" callout

…and inject it after the first H2. This is the single most impactful
"is this content unique?" signal we can add cheaply, because:
  1. AI articles are statistically similar to each other; original
     assets break that pattern.
  2. HTML tables and TL;DR callouts are readable even without frontend
     rendering libraries.
  3. Readers visibly perceive higher quality.

The asset is generated by the same LLM in a single short call. No
images, no external rendering pipeline — pure HTML/SVG-friendly markup
that WordPress passes through cleanly.
"""
from __future__ import annotations

import json
import random
import re
from typing import Optional

from .llm import LLMClient
from .logging_utils import log


ASSET_PROMPT = """You are producing an original visual asset for an article.
Pick the format that best fits the article's topic and intent. Return ONLY
a JSON object with this shape:

{{
  "format": "table" | "tldr",
  "content": "<the asset content, see format rules below>"
}}

FORMAT RULES:

  "table"
    content is a complete HTML table comparing 3-5 things relevant to
    the article. Format: <table><thead>...<tbody>...</table>.
    Include a header row and 3-6 body rows. No inline styles.

  "tldr"
    content is HTML: <div class="tldr"><strong>TL;DR:</strong> ...</div>
    Inside, 2-4 short factual bullet points as a nested <ul>.

CHOICE GUIDE:
- If the topic is process / workflow / decision flow → table with clear steps.
- If the topic involves comparing options / tools / approaches → table.
- Otherwise → tldr.

Do NOT include any specific company / brand / person names.

Article title: {title}
First section H2s: {h2s}

Return ONLY the JSON object."""


def _strip_fences(text: str) -> str:
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```[a-z]*\n", "", text)
        text = re.sub(r"\n```$", "", text)
    return text.strip()


def _render(format_: str, content: str) -> str:
    if format_ == "mermaid":
        log.warning("original_asset.mermaid_disabled")
        return ""
    if format_ == "table":
        cleaned = content.strip()
        if not re.search(r"<table[\s>]", cleaned, flags=re.I):
            return ""
        return f'<figure class="oc-asset oc-asset--table">{cleaned}</figure>'
    if format_ == "tldr":
        return f'<aside class="oc-asset oc-asset--tldr">{content.strip()}</aside>'
    log.warning("original_asset.unknown_format=%r", format_)
    return ""

def generate_asset(title: str, html: str) -> Optional[str]:
    """Generate ONE original asset block. Returns rendered HTML or None."""
    h2s = re.findall(r"<h2[^>]*>(.*?)</h2>", html, flags=re.I | re.S)[:5]
    h2s = [re.sub(r"<[^>]+>", "", h).strip() for h in h2s]

    try:
        raw = LLMClient().complete_text(
            ASSET_PROMPT.format(title=title, h2s=json.dumps(h2s)),
            max_tokens=600,
        )
        if not raw:
            return None
        data = json.loads(_strip_fences(raw))
        rendered = _render(data["format"], data["content"])
        log.info("original_asset.ok format=%s", data.get("format"))
        return rendered or None
    except Exception as exc:
        log.warning("original_asset.fail err=%s", exc)
        return None


def inject_after_first_h2(html: str, asset_html: str) -> str:
    """Insert the asset block right after the first </h2> closing tag.
    Falls back to prepending if no <h2> is present."""
    if not asset_html:
        return html
    match = re.search(r"</h2\s*>", html, flags=re.I)
    if not match:
        return asset_html + "\n" + html
    pos = match.end()
    return html[:pos] + "\n\n" + asset_html + "\n" + html[pos:]


def enhance(html: str, title: str) -> str:
    """One-shot: generate an asset for the article and inject it."""
    asset = generate_asset(title, html)
    if not asset:
        return html
    return inject_after_first_h2(html, asset)
